### ISSUE TITLE
Shift+`◄`/`►` do not scroll cursor into view

### ISSUE THREAD

**Issue by mahi2003** [c3d/DB48X-on-DM42#1003]
* Enter something wider than the display. For example: `"ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"`
* While still in entry mode with the cursor at the end, press Shift+`◄` to return to the beginning of the string → :x: The cursor moves correctly to the beginning of the line, but the screen does not update. Press `►` `◄` to make the screen update
* Now press Shift+`►` to go to the end of the line → :x: Same issue. Press `◄` `►` to update

**Comment by c3d** [comment]
Thanks for the report. Fix available on the `dev` branch.

**Comment by mahi2003** [comment]
✔️ Confirmed fixed in 0.7.9!
