### ISSUE TITLE
Interactive stack: `Edit` then `EXIT` still adds value to stack

### ISSUE THREAD

**Issue by mahi2003** [c3d/DB48X-on-DM42#1021]
First of all: I love the new interactive stack! Thank you!

With a stack like...

```
1
2
3
```

... press the left/up arrow to enter the interactive stack and select, for example, the second stack level. Press ´Edit´. The calculator enters entry mode with value `2`. The stack is still unaltered (unlike when you would have used `Pick`).

Press `EXIT` to abort the entry mode. The stack now gets the selected value appended (as if we did use `Pick`) even though we canceled.

```
1
2
3
2
```

**Comment by c3d** [comment]
I think that the real problem is that `Edit` ought to edit level 2 in that case, but really brings level 2 into the editor, and then runs the editor normally (hence you getting the result on the first level of the stack).

**Comment by c3d** [comment]
The last step of the description needs to be adjusted to mention that you need to type `EXIT` twice, once to exit interactive stack mode, the second one to exit editor mode. And indeed, the second `EXIT` does add the edited item to the stack.

If you select `2` then `1` then `3`, the editor line is `2 1 3`. Pressing `EXIT` in that state only enters the value `3`, i.e. the last one picked.

**Comment by mahi2003** [comment]
✔️ Confirmed fixed in 0.7.11
