### ISSUE TITLE
Interactive stack: Block keyboard input?

### ISSUE THREAD

**Issue by mahi2003** [c3d/DB48X-on-DM42#1022]
I noticed that while in the interactive stack the calculator still accepts normal keyboard entry. For example, with stack...

```
1
2
3
```

... press the left/up arrow to enter the interactive stack and select, for example, the second stack level.

* Now press the `SIN` button and the sinus of stack level 1 is calculated
* Press the `x↔y` button and stack levels 1 and 2 are swapped
* Press the `+` operator and stack levels 1 and 2 are added
* Press numeric button `1` and the calculator enters entry mode even though still in the interactive stack

On the HP 48/50 the interactive stack blocks all keyboard entry other than those related directly to the stack manipulation (the soft keys, up, down, backspace, ENTER, ON, NXT, PREV, COPY).

**Comment by c3d** [comment]
You are correct, this is the expected behavior. The key blocking needs to be implemented.

**Comment by mahi2003** [comment]
✔️ Confirmed fixed in 0.7.11
