### ISSUE TITLE
Interactive stack: Menu items are painted incorrectly

### ISSUE THREAD

**Issue by mahi2003** [c3d/DB48X-on-DM42#1024]
* Have at least one item on the stack
* Open the `SolverMenu`. Note how the the `Diff`, `Poly`, `Solve`, `Num` and `Symb` menu entries have a folded corner to indicate they are folders (or sub menus)
* Press left/up arrow to enter the interactive stack. The menu changes to that of the interactive stack. The menu entries that are in the same location as the previous sub menus (`Keep`, `Roll↑`, `Roll↓`, `Pick`and `→List`) now have the same folded corners

Same issue, but differently:

* Have at least one item on the stack
* Press left/up arrow to enter the interactive stack. The menu changes to that of the interactive stack
* Press the `VAR` button on the keyboard and observe what happens to the shifted menu entries: `DupN`, `DropN`, `Keep`... become `DupN►`, `DropN►`, `Keep►`

**Comment by c3d** [comment]
Good catch. If my theory is correct, I think that the same thing should be true with the Help menu.

**Comment by mahi2003** [comment]
✔️ Confirmed fixed in 0.7.11
