### ISSUE TITLE
Add preference to make menus persistent

### ISSUE THREAD

**Issue by spiff72** [c3d/DB48X-on-DM42#1046]
I like to see the menu buttons all the time - specifically to be able to see my variables.

Currently, if you press the exit key twice, the menu disappears, and I have to press the VAR button again to bring it back.  I also find it jarring when I have a folder that contains no variables - I would rather see blank buttons across the bottom than have it disappear when I have the variables displayed and switch to a different folder that is empty.

So my ask is to see if it's possible to have a toggle in settings that allows for persistence of the variables menu buttons.  I'm not sure if this is valid outside of the variables menu, but thought I would ask!

**Comment by c3d** [comment]
I see two slightly different requests here:

- A preference controlling whether `EXIT` clears menus
- A preference controlling whether blanks menus should show on screen.

I'd rather make it two distinct preferences.

**Comment by c3d** [comment]
Implemented with two pairs of settings:

- `HideEmptyMenu` / `ShowEmptyMenu`
- `ExitClearsMenu` / `ExitKeepsMenu`

**Comment by spiff72** [comment]
Fantastic - thanks!
