### ISSUE TITLE
Add Units for Flow Rate l/s, m3/hr, m3/s, gpm...

### ISSUE THREAD

**Issue by BTF-NGU** [c3d/DB48X-on-DM42#1060]
It is possible to include unit conversions (not included in HP Calculator). This has always been a gap.
Flow
m3/hr <--> l/min
l/min <--> l/s
m3/hr <--> l/s
m3/hr <--> US GPM
l/s <--> US gpm
l/min <--> US gpm
m3/s <--> US GPM

**Comment by c3d** [comment]
Yes.

First, in the current release, you can add this directly using the `units.csv` configuration file.

I will add them in the next release.
