### ISSUE TITLE
Interactive stack: `Swap` does not work at level n-1

### ISSUE THREAD

**Issue by mahi2003** [c3d/DB48X-on-DM42#1067]
Assume a stack of at least 4 items. For example:

```
1
2
3
4
```

* Press left/up arrow to enter the interactive stack (level 1 is selected)
* Press `Swap` or `x↔y` → Stack levels 2 and 1 are swapped
* Press left/up arrow (level 2 is selected)
* Press `Swap` or `x↔y` → Stack levels 3 and 2 are swapped
* Press left/up arrow (level 3 is selected)
* Press `Swap` or `x↔y` → :x: Nothing happens while I expected stack levels 4 and 3 to swap

**Comment by c3d** [comment]
Good catch, @mahi2003. Will be fixed in the next release.
