### ISSUE TITLE
Evaluating `1/sqrt(epsilon0*mu0)` with variable `M` set

### ISSUE THREAD

**Issue by c3d** [c3d/DB48X-on-DM42#1110]
This recalls the value of variable `M` and evaluates it, which is wrong.

**Comment by Wiljea** [comment]
It seems to me that the problem with **1/SQRT(ε0ˑμ0)** is not with the numerical value of **c** (correctly evaluated here) but only with the missing simplification of physical units:
**(1ˍFˑ1ˍH)^0,5=1ˍm/s**   OR   **1ˍFˑ1ˍH=(1ˍm/s)^2**.
**Possible solution** might be to attach an equivalence to either definition of **1ˍF** or **1ˍH**:
**1ˍH=(1ˍm/s)^2/1ˍF**  OR  **1ˍF=(1ˍm/s)^2/1ˍH**
Was it what you meant here ?

**Comment by prismv** [comment]
Yes, the value is right in the example given in #1105, but the units $\sqrt{\mathrm{F}\cdot\mathrm{H}}$ are not converted to most basic SI unit: s.

Though I don't understand the issue headline ...

**Comment by prismv** [comment]
I tried the current dev version 0709be1.
Some factoring issue is solved now by showing {c}m/(F<sup>½</sup>H<sup>½</sup>). I see also the point that with strict compatibility to HP48/50 one has to perform UBase ("Base") manually. 

Nevertheless it might be a nice optional (?) feature to perform this last step automatically?!
