### ISSUE TITLE
Default font: Character `v` is offset one pixel

### ISSUE THREAD

**Issue by mahi2003** [c3d/DB48X-on-DM42#1117]
This is just a cosmetic issue with no further impact.

The lower case `v` character is offset one pixel higher than the other characters in the default font. Just type something like `uvwx` and the issue should be visible. It's visible on entry, in the stack and even in the help.

**Comment by c3d** [comment]
There is a subtle rounding problem in the conversion.
I manually adjusted the `v` glyph to address it.

Please check in the upcoming release, I believe that it looks good now.
