### ISSUE TITLE
Remove `._*` files from release archives

### ISSUE THREAD

**Issue by mahi2003** [c3d/DB48X-on-DM42#1125]
The release archives contain a lot of dot-underscore files (`._*`) of exactly 163 bytes. Almost every file has an accompanying dot-underscore file (for example `db48x.md` and `._db48x.md`).

The dot-underscore files appear to be something from MacOS and serve no purpose for DB48X/DB50X. These files should be stripped from the release archives.

**Comment by c3d** [comment]
Good point. Thanks, I'll make sure they are removed in the next release.

**Comment by c3d** [comment]
Interesting that the files in question do not show up when I do a
`tar tvfz db48x-v0.7.14.tgz`.
