### ISSUE TITLE
Access to gravitational constant G leads to an infinite loop (reset necessary).

### ISSUE THREAD

**Issue by Wiljea** [c3d/DB48X-on-DM42#1128]
This is the only constant featuring this problem. This appears with shift G or after ASN(G).

**Comment by mahi2003** [comment]
Appears to be a typo in the unit in file `constants.cc`:

`"6.67259E-11_m^3/(s^2•kg)"`

should be

`"6.67259E-11_m^3/(s^2*kg)"`

(substitute `•` with `*`)
