### ISSUE TITLE
Integrate equations from Jean Wilson

### ISSUE THREAD

**Issue by c3d** [c3d/DB48X-on-DM42#1129]
Integrate the electricity related equations provided by Jean Wilson.

**Comment by Wiljea** [comment]
I will soon have a more complete and revised version for electricity and much more items already written that I will send to you via email.

**Comment by Wiljea** [comment]
And I will eventually provide the testing values for the new formulas that I decided to add to the Electricity chapter. For instance in the sections "E Field Finite Line", "Resistivity & Conductivity", "Drift Speed & Current Density", etc.
