### ISSUE TITLE
A suggestion to solve the radian unit problem of the angular frequency ω

### ISSUE THREAD

**Issue by Wiljea** [c3d/DB48X-on-DM42#1221]
In physics the angular units of the angular frequency ω is usually r/s (ω_r/s) but the numerically required radians, strictly speaking, appear or disappear depending on the equations, as in the following examples:
> for "Waves":
>     **"'(vs_(cm/s))=(sm_cm)·(ω_(r/s))·SIN((k_(r/cm))·(x_cm)-(ω_(r/s))·(t_s)+(φ_r))' "**
>     **"'(as_(cm/(s^2)))=-(ω_(r/s))^2·(s_cm)' "**
> or for "RLC Current Delay"
>     **"'(XC_Ω)=1/((ω_(r/s))·(C_μF))'** "
> or for "Simple Pendulum"
>     **"'(ω_(r/s))=√(Ⓒg/(L_cm))' "**
All these equations (more than 20 in the Equation Library) currently lead to incompatible unit errors. Unlike several environments where the angles do not really have units (or are only in radians by default, like in Fortran or in HP50g, etc.) here the db48x assigns the angles their explicit units (rad, grad, ° ). Therefore, instead of tweaking exceptions with the parsing algorithm a simple solution would be to add or remove radians explicitly as needed, for instance:
>     **"'(vs_(cm/s))=(sm_cm)·(ω_(r/s))/(1_r)·SIN((k_(r/cm))·(x_cm)-(ω_(r/s))·(t_s)+(φ_r))' "**
>     **"'(as_(cm/(s^2)))=-(ω_(r/s)/(1_r))^2·(s_cm)' "**
>     **"'(XC_Ω)=1/((ω_(r/s)/(1_r))·(C_μF))' "**
>     **"'(ω_(r/s))=(1_r)·√(Ⓒg/(L_cm))' "**
It is not a big deal. Let's have the opinion of the author.

**Comment by c3d** [comment]
I agree. This is how I solved it in the `Eccentric Columns` and `Simple Slope` equations.

**Comment by Wiljea** [comment]
Ok, fine, I'll do it after a thorough check for all instances of such problem.
