### ISSUE TITLE
`Inconsistent units error` converting `lb` to `kg` or `g` 

### ISSUE THREAD

**Issue by nickapos** [c3d/DB48X-on-DM42#1227]
Today I realised that when I try to convert lb to kg I get inconsistent units error
![IMG_0839](https://github.com/user-attachments/assets/18036f5b-eab9-418f-a3ac-525b1a6b84bd)
Version is 0.8

**Comment by c3d** [comment]
It's weird. It works for me, and works for the [on-line version](https://48calc.org). Could you please share:
1. The state file
2. The `units.csv` file

Is it possible that you have some customization in `units.csv`?

**Comment by nickapos** [comment]
[units.csv](https://github.com/user-attachments/files/17220254/units.csv)
[Demo.zip](https://github.com/user-attachments/files/17220264/Demo.zip)

i think I added some entries in the cycle section, nothing else. Please let me know if you need anything else.

**Comment by c3d** [comment]
With your file, I have the same problem. So now I can investigate.

There is another problem too: in the `Quick` menu, if I hit `Next` I get tons of garbage. Well, not exactly garbage, more precisely units from the builtin `Length` units.

**Comment by c3d** [comment]
Fixed one of the issues (garbage in `Quick` menu), but other problems remain.

The issue seems to derive from this change in the `units.csv` file:

```patch
@@ -21,6 +21,9 @@
 "in",           "mm"
 "mm",           "cm"
 "cm",           "in"
+"ft",           "m"
+"lb",           "kg"
+"oz",           "g"
 "USD",          "EUR"
 "EUR",          "CHF"
 "CHF",          "USD"
```

**Comment by c3d** [comment]
The problem was that the `=Cycle` section of `units.csv` was incorrectly used for the definition of `lb`, leading to an invalid definition that caused the problem. This will be fixed by skipping the `=Cycle` section while looking for unit definitions.
