### ISSUE TITLE
Add assignment operations

### ISSUE THREAD

**Issue by c3d** [c3d/DB48X-on-DM42#1262]
In order to be able to document the built-in equations in a way that is usable in practice, we need to have a quick way to describe a number of variables.

A possible approach is to have an `assignment` object that is similar internally to unit objects, but with a `=` separator and a name on the left. This would work like the `▶` operator on the HP50G.

Proposed syntax:

```
A=50_m
B='30_cm+25_mm'
```

Note that the syntax cannot be accepted inside algebraic expressions, but it could be rendered as:

```
50_m▶A
'(30_cm+25_mm)▶B'

```

This behaves like `STO` but returns the input value on the stack.

**Comment by Wiljea** [comment]
So contrary to STO it doesn't consume the value on level 1 of the stack, isn't it ?

**Comment by c3d** [comment]
Separate assignment operation and assignment object.

The assignment object also tags the result.
