### ISSUE TITLE
ToPolar for vector is not working correctly for Deg angular mode

### ISSUE THREAD

**Issue by prismv** [c3d/DB48X-on-DM42#1270]
As a follow-up of #1238 I noticed that ToPolar for vector has still an issue, if Deg angular mode is enabled.

For instance `[0 2]` results in `[2. 1/2°]`.

Results for this example in Rad angular mode, `[2.000 1.571r]` (with FIX 3), and in nxπ, `[2. 1/2πr]`, seems to be correct.

(Sorry for the new issue. It's not possible for me to re-open a closed issue.)

**Comment by c3d** [comment]
Thanks @prismv for reporting. Sorry for the delay looking into this.
