### ISSUE TITLE
"Vec →"  leads to "/ error: Inconsistent units" in Equation Library

### ISSUE THREAD

**Issue by Wiljea** [c3d/DB48X-on-DM42#1276]
In the Equation Library, it may happen that we have a vector containing two or more calculated values having different units, for instance:
[ λ=0.00000 00166 67 C/m Er=5 991.70119 159 N/C ]

and if we try to extract the components on separate levels of the stack with the function 
"Vec →", we have this error condition:
"/ error: Inconsistent units"

but as soon as we cancel this message, the extraction is performed correctly, so the error message is superfluous.

**Comment by c3d** [comment]
The error message is generated checking if we have a polar vector, which is done by checking if the unit converts to an angle. So it only happens on 2D or 3D vectors with a unit in 2nd or 3rd position.
