### ISSUE TITLE
Wrong value of ATAN & EXP applied to a ratio of mixed units

### ISSUE THREAD

**Issue by Wiljea** [c3d/DB48X-on-DM42#1277]
For instance:  1.5_m  5_cm  ATAN leads to:
ATAN(1.5_m/5_cm) = ATAN(0.3_m/cm) = 1 669.92442 34 ° 
ATAN(0.3_m/cm) = 29.14567 94478 r (rad equivalent)
which is obviously wrong because if BASE was performed before, this will give:
ATAN(30) = 88.09084 7567 °

which is correct. Therefore BASE should be performed apriori in such cases as in "E Field Finite Line" exemple 2.

**Comment by Wiljea** [comment]
The same is seen for EXP(-t/(R·C) with C=50_μF R=100_Ω t=2_ms in "RC Transient" where this leads to:
EXP(-¹/₂ ₅₀₀ ms/(μF·Ω)) = 999.60007 9989
which is wrong because, using base
BASE(-¹/₂ ₅₀₀ ms/(μF·Ω)) = -²/₅  =>  EXP(-t/(R·C) = 0.67032 00460 36

**Comment by c3d** [comment]
Duplicated by mistake in #1301, which I now closed.

This will be fixed in the next release. Thanks for reporting.

**Comment by Wiljea** [comment]
I think that we should close this issue ??

**Comment by Wiljea** [comment]
Done.
