### ISSUE TITLE
BUILD.md suggest coreutils install for MacOS

### ISSUE THREAD

**Issue by cdmackay** [c3d/DB48X-on-DM42#1279]
BUILD.md notes that the project requires _tac_, but doesn't suggest how to get it on MacOS.

It might suggest:

brew install coreutils

**Comment by c3d** [comment]
Thanks for reporting, @cdmackay. The suggestion should be removed, since we don't use `tac` anymore during the build.

**Comment by c3d** [comment]
Actually, I was wrong, still used while computing the checksum. I will follow your suggestion.
