### ISSUE TITLE
Units conversions K <=> °C <=> °F are required in "Gases" of Equation Library

### ISSUE THREAD

**Issue by Wiljea** [c3d/DB48X-on-DM42#1287]
I think there is an old unresolved issue related to that topic.

**Comment by c3d** [comment]
> I think there is an old unresolved issue related to that topic.

Yes, it's #1064. I have a semi-working prototype with an approach that uses general expressions, and would therefore even enable non-linear conversions, e.g. Dalton temperature scale or dB to power.

Closing this one as a duplicate of #1064.
