### ISSUE TITLE
Slow editing on battery

### ISSUE THREAD

**Issue by c3d** [c3d/DB48X-on-DM42#13]
Editing while on battery power is really slow

**Comment by balta1980** [comment]
Also on battery functions like sin, log, square root crash the calc.
 On battery, even doing, nothing the battery drains very fast.

**Comment by balta1980** [comment]
I figured out that if the calc did not crash on battery when run for example log just got freeze. When plugged to USB again the function finish correctly

**Comment by balta1980** [comment]
I am in love with this program.

**Comment by c3d** [comment]
> I figured out that if the calc did not crash on battery when run for example log just got freeze. When plugged to USB again the function finish correctly

Yes, this is consistent with my experience. My suspicion is that there is something wrong with how I use the timers to refresh the cursor. This is high on my to-do list.

**Comment by c3d** [comment]
> Also on battery functions like sin, log, square root crash the calc.

Probably more like a hang, as you noted. This is #12 

> On battery, even doing, nothing the battery drains very fast.

Interesting. How do you evaluate / measure that?

**Comment by c3d** [comment]
I believe that this was solved in [version 0.2](https://github.com/c3d/DB48X-on-DM42/releases/tag/v0.2). Please re-open if the problem still exists.
