### ISSUE TITLE
Occasional failure of Simple Deflection test in Column and Beams

### ISSUE THREAD

**Issue by c3d** [c3d/DB48X-on-DM42#1325]
The following test occasionally fails

```c++
    step("Solving Simple Deflection")
        .test(CLEAR, ID_EquationsMenu, F2, RSHIFT, F3)
        .test("10_ft", NOSHIFT, F2)
        .test("17_ft", NOSHIFT, F3)
        .test("29000000_psi", NOSHIFT, F4)
        .test("40_in^4", NOSHIFT, F5, F6)
        .test("20_ft", NOSHIFT, F1)
        .test("3687.81_ft*lbf", NOSHIFT, F2)
        .test("674.427_lbf", NOSHIFT, F3)
        .test("102.783_lbf/ft", NOSHIFT, F4)
        .test("9_ft", NOSHIFT, F5)
        .test(F6, LSHIFT, F1)
        .expect("y=-1.52523 29401 2 cm")
        .test("1_in", F1, LSHIFT, F1)
        .expect("y=-0.60048 54094 96 in");

```

It fails at the `1_in` case with an inconsistent unit error message.

**Comment by c3d** [comment]
The underlying problem is a cascade of failures as follows:

1. The unit factor `o / u` in `unit::convert` is not a `real` for a conversion that should succeed.

2. The reason is that one fo the unit expressions contains a `symbol` for `in` in a multiplication

3. This is because in `unit::mode` the lookup for `in` failed

4. This happens because the evaluation of `254/10_mm` by `object::parse` returns a really bogus return size.

5. This happens because the length returned by the `integer` parser is `s - p.source`, but `s` has not been adjusted during a garbage collection...

6. The garbage collection happens while building the fraction object for `254/10`.

Fixing by keeping a garbage-collected pointer for `s` while building the fractions.

**Comment by Wiljea** [comment]
May be this is related to the frequent occurrences of "Inconsistent units" error in the Equation Library as in ISSUE#1323 ?
