### ISSUE TITLE
"Inconsistent units" in a legitimate algebraic expression

### ISSUE THREAD

**Issue by Wiljea** [c3d/DB48X-on-DM42#1356]
When 2 additive terms of an algebraic expression have different units, we get the "Inconsistent units" error message even if they are compatible through CONVERT. For instance in the following sum (1) we find units of electrical field (N/C) and magnetic field (T) (with the relation N/C=T*m/s):

Ey=200_(N/C)   Bz=350_T  β=0.995  γ=10.01252  to be used in the sum
(1)   'γ*((Bz_T)-β/Ⓒc*(Ey_(N/C)))'  followed by "=" gives
 10.01252  350_T  0.00000 06637 93 s·N/(m·C)   and the error message

If you do 1_T  CONVERT => 0.00000 06637 93 T then you terminate by  - * to obtain the legitimate answer: 3 504.38321 361 T

I am not sure but I suspect that such problem might explain the frequent occurrences of this error message when solving in the Equations Library.

**Comment by prismv** [comment]
Solving or EvalEq of `'Q=√((L_H)/(C_F))/(R_Ω)'` also fails due to inconsistent units. Not sure, if an explicit `Q_1` might help here.

PS: right side saved then as `EQur` (see post below)

**Comment by Wiljea** [comment]
@prismv  
Suppose we have R=100_Ω  C=4_nF  L=100_mH, what works is using UBASE either in 
'UBASE(√((L_H)/(C_F))/(R_Ω))'  =50.00000 00001
Or in
'ROOT(Q=UBASE(√((L_H)/(C_F))/(R_Ω));[Q];[1])'  =>[ Q=50.00000 00001 ]

**Comment by prismv** [comment]
Indeed `'ROOT(Q=UBASE EQur;[Q];[1])'` (with `EQur` is the right side of equation) works, but without `UBASE` it does not work. Therefore it seems to be another example for the issue you report here.
