### ISSUE TITLE
Directory not properly initialized when not on first screen page

### ISSUE THREAD

**Issue by prismv** [c3d/DB48X-on-DM42#1361]
If a directory is shown on second screen of HOME, i.e. navigating with arrow (F6) is necessary, then the variables in this directory are at first not available from VariablesMenu.

Only after exiting and reentry of VariablesMenu the variables can be evaluated, read or written by menu actions.

See `test` directory in [RA_00.48S.txt](https://github.com/user-attachments/files/17881629/RA_00.48S.txt)

If a directory is shown on first screen of HOME, this issue does not apply.

**Comment by c3d** [comment]
Yes, it is necessary to restore the first page in the menu when changing directories.

**Comment by c3d** [comment]
Fix implemented on the `dev` branch. This will be fixed in the next release.

**Comment by prismv** [comment]
Checked and okay! Thanks.
