### ISSUE TITLE
Removing 'ΣData' from the VAR menu?

### ISSUE THREAD

**Issue by orome** [c3d/DB48X-on-DM42#1368]
Is there a way to remove 'ΣData'  from the VAR menu? The usual method (' + choose name, then PurgeAll) fails with "Invalid Name". In fact the name isn't even italicized in the display (as other names are using this method).

**Comment by c3d** [comment]
`PurgeAll` excludes all special variables such as `ΣData` or `PPar`. The rationale is that operations on these variables update the current directory, and that you don't want to mistakenly purge more global settings.

Please use `Purge` instead.

**Comment by c3d** [comment]
Since it is confirmed that the solution works, closing this issue.
