### ISSUE TITLE
"Dead-End" Menu for CAT[ALOG]

### ISSUE THREAD

**Issue by msrgm** [c3d/DB48X-on-DM42#1372]
Sometimes using the CATALOG in what has already been described as an inefficient way (i.e. SHIFT + to invoke CAT) and lazily forwarding  through it using the F6 key to find the function I want, I get to what I call a "dead-end" menu, where the function keys F1 to F6 are all assigned functions but there are no forward or back arrows on F6 and SHIFT F6.  SO you cannot move forward of backward through the CATALOG if this happens.  You can of course EXIT.  

Please see the attached photo of what I have referred to as the "dead-end" menu.  I tried to take a screenshot using the calculator (SHIFT DISP) but pressing the SHIFT key discarded the "dead-end" menu, so there was no screenshot :-)
![Dead-End_Menu](https://github.com/user-attachments/assets/c3cba032-9d79-4e8a-9034-8d4cd032d680)

**Comment by c3d** [comment]
I have a vague idea of how we can get there. There will be a tentative fix in v0.8.8.
