### ISSUE TITLE
arcsin does not correctly adjust angle unit for input 1

### ISSUE THREAD

**Issue by HappyDB48XUser** [c3d/DB48X-on-DM42#1374]
I found a peculiar behaviour of SIN-1 (arcsin). You can replicate this on the DM42 version 0.8.7, iPhone version 0.8.6 and also on the web-version so I'm sorry if this has been reported already. 

Enter 90 and press SIN gives 1
Now press SIN-1 and you will get: 3,14159..... (degrees in degrees mode / radians in radians mode)

For values close to 1 it seems to work properly.

<img width="427" alt="SIN-1" src="https://github.com/user-attachments/assets/b7dd5cc8-a262-4c30-bdee-6c15287c4a24">

Thanks a lot for a great and better version of RPL.

**Comment by c3d** [comment]
Hi @HappyDB48XUser. Nice to see someone pick up a GitHub username based on the project...

As for the bug you reported: nice catch. This is a case where DB48x is supposed to return an exact integer value, but somehow the code adjusting the angle unit was messed up. I'm surprised the test case was not in the test suite, I will add it.
