### ISSUE TITLE
Possible correction to check_qspi_crc in db48x/tools for Fedora WSL?

### ISSUE THREAD

**Issue by msrgm** [c3d/DB48X-on-DM42#1377]
I am closing this issue, because it is more of a misunderstanding of mine.  

The script check_qspi_crc in the release of db48x/tools refers to crc32 (line 27) but there seems to be no crc32 program/function/command.  It looks like forcecrc32 (source is forcecrc32.c) in tools/forcecrc32 calculates the "correct" CRC-32 for the current DM42_qspi_3.x.bin

However, I also see a hard-coded CRC value in adjust_crc in the db48x/tools directory, so there seems to more going on here.

The script in the build of 0.8.7 is here: https://github.com/c3d/db48x/blob/stable/tools/check_qspi_crc

**Comment by msrgm** [comment]
OK, so it seems the checksum should be run be forcecrc32 and not the "native" cksum in Fedora.

**Comment by msrgm** [comment]
Closing because it is not an issue.

**Comment by prismv** [comment]
It _is_ an issue, because the dependency on `crc32` program is not documented. E.g. "perl-Archive-Zip" for Fedora. Or is this not correct, @c3d ?

@msrgm If you see it also, you could re-open this issue and adjust title of issue.

**Comment by msrgm** [comment]
Hi prismv, I have raised it with Christophe and he will update the installation documentation.

**Comment by prismv** [comment]
Hi Mark,

great that docs will be improved.

Best regards
Ralf

09.12.2024 11:25:54 Mark Ringrose ***@***.***>:
