### ISSUE TITLE
Bias on RANDOM function with integer parameters

### ISSUE THREAD

**Issue by skai111** [c3d/DB48X-on-DM42#1378]
DB50X v.0.8.7 Hardware DM42n
RANDOM with integer parameters gives bias to end values.
According to help file, RANDOM with integer parameters should generate integer values within an interval including endpoints.
I would therefore expect all integers within this interval to be uniformly generated.

However, end points are only generated with half the probability.
Help file does not explain this, maybe something is missing in the help file?

E.g.  Roll a dice 6000 times to illustrate the issue:

``` rpl
«
    0 RDZ         @ random seed
    [ 0 0 0 0 0 0 ]  @ result array
    1 6000 START
        1 6 RANDOM @ note integers at endpoints
        DUP2 GET 1 + PUT
    NEXT
»
```

result from one run

``` rpl
[ 619 1228 1182 1171 1212 586 ]

```

Endpoints roughly get half the probability of interior points.

**Comment by c3d** [comment]
Adjusted the way computation for integer ranges was done to avoid the offset. This actually simplifies the code overall.

With the change, your benchmark gives:

``` rpl
[ 1 014 967 1 009 1 050 1 005 955 ]
```

The following modified version of your benchmark to check negative test cases:

``` rpl
«
	0 RandomSeed                    @ random seed
	[ 0 0 0 0 0 0 0 0 0 0 0 0 0 ]   @ result array
	1 13000
	start
		-6 6 Random 7 +
		@ note integers at endpoints
		Duplicate2 Get 1 + Put
	next
»
```

gives the following results:

``` rpl
[ 1023 1010 978 1067 1025 974 971 1015 998 975 1011 935 1018 ]
```
