### ISSUE TITLE
DERIVATIVE rendering is wrong in compatibility rendering mode

### ISSUE THREAD

**Issue by c3d** [c3d/DB48X-on-DM42#1384]
This is lifted from issue #1383 

State file containing `∂x` is written as `DERIVATIVEx`, which does not parse back correctly.

Example given in #1383 by @prismv:

```rpl
Directory {
	deriv
		Directory {
			dfval 'f′(x)|x=Ⓒπ÷4'
			f′ 'DERIVATIVEx(f(x))'
			f 'x²+x·sin x'
		}
	perf
		Directory {
			Speed
				«
					Ⓒπ →Num 6.30
					÷
					«
						1 10000
						start
							Duplicate sin Drop
						next
					»
					TimedEval
				»
		}
}
'test' STO
UpperCase
VariablesMenu
 HomeDirectory test deriv
```

I suspect that the `UpperCase` setting matters to this test case.

**Comment by c3d** [comment]
The spelling `DERIVATIVEx` on output is the problem.

It's supposed to be spelled `∂x` and is parsed specially, so if it's written in the state file as `DERIVATIVEx`, then the special parsing does not work.

**Comment by c3d** [comment]
With experimentation, I could confirm that this only shows in compatibility mode, like `UpperCase`.

**Comment by prismv** [comment]
Fixed for my case. Could be closed (I cannot because not the issuer)
