### ISSUE TITLE
Continuation of issue #1392: Please try to switch Sym for tests ...

### ISSUE THREAD

**Issue by prismv** [c3d/DB48X-on-DM42#1397]
v0.8.8-18-9271 aka 0.8.9, DM42, compiled with gcc version 10.3.1 20210824 (release) (GNU Arm Embedded Toolchain 10.3-2021.10)

`9999 555 COMB` fails silently with HwFP set (prec. 7 or 16), if `Sym` is unset, i.e. `MODES` shows `NUMERICALRESULTS`.

If `Sym` is enabled, "Number is too big" error is shown. In contrast to DM42 the simulator showed 0. (not on all systems though ...), if 'Sym' is disabled.

I believe that I already gave the proper report in #1392 together with my `MODES` output information. So it would have been easier to be able to input this more specific report also therein.

EDIT: simulator was re-tested on another system with different result. (DM42 firmware was also re-compiled and tested again).

**Comment by c3d** [comment]
Reproduced. The problem is indeed different for `NumericalResults`.
