### ISSUE TITLE
Implement ->NUM

### ISSUE THREAD

**Issue by c3d** [c3d/DB48X-on-DM42#255]
Implement a `->NUM` operation to be able to convert fractions to real numbers.

**Comment by spiff72** [comment]
Is this ->NUM function available as a shortcut on the KB?

**Comment by lmamakos** [comment]
This still doesn't quite work completely to evaluate an expression.  So I do this sequence one the keyboard:
```
355
113
/
𝝅
-
``` 

and I'm left with `'355/113-𝝅'` on the stack.   When I try to invoke `➝Num`, I get a "Bad argument type" error reported.   

On my HP-48G, the `355 133 /` evaluates immediately, and subtracting `𝝅` from it can be then simplified to a number using `➝Num`.

I'm running version 0.4.2 on my DM42.

**Comment by c3d** [comment]
> Is this ->NUM function available as a shortcut on the KB?

The intent is for it to be mapped to the "EEX" key (which would be cycling between possible representations of a number). It's not there yet.

**Comment by c3d** [comment]
> This still doesn't quite work completely to evaluate an expression. So I do this sequence one the keyboard:
> 
> ```
> 355
> 113
> /
> 𝝅
> -
> ```
> 
> and I'm left with `'355/113-𝝅'` on the stack. When I try to invoke `➝Num`, I get a "Bad argument type" error reported.

That's a bug. I filed #345.

 
> On my HP-48G, the `355 133 /` evaluates immediately, and subtracting `𝝅` from it can be then simplified to a number using `➝Num`.

There is a change in behaviour there between the HP48 and HP50. The HP48 does not have fractions or big numbers. The HP50 and DB48X do support this. So the HP50 behaves like DB48X in that respect (except for the bug in `->NUM` 😄 )

The HP50 also has a flag indicating if you want to immediately evaluate as numeric. This is not implemented yet. I filed #346.

BTW, when you find a problem like this, I encourage you to file an issue for each problem rather than mention it in a comment on some other issue. That ensures it will be addressed some day 😄  

> 
> I'm running version 0.4.2 on my DM42.

**Comment by lmamakos** [comment]
Thanks!  I wasn't sure if you wanted to re-open this issue or not; I'll keep that in mind for next time.  Thanks for being so responsive and for the wonderful software.
