### ISSUE TITLE
Implement object switching on the EEX key

### ISSUE THREAD

**Issue by c3d** [c3d/DB48X-on-DM42#273]
Implement a smart object switching on the EEX key:

- Switch between fractions and decimal representation
- Switch between polar and rectangular for complex numbers
- Switch between vector and and list form
- Switch units for unit objects
- Switch bases for based numbers?

How should the feature be named? What about `AutoCycle`?

**Comment by camillew** [comment]
Maybe ModeCycle? Or Rep[resentation]Cyle?
polar<->rect and list<->vector would work as cycle, fraction<->decimal too (->Num ->Q) but what about unit objects?

Would it be specialized for some classical pairs, like (cm<->in, km<->mi, etc.)? But then, would fractions be allowed in unit objects? As in, if we have (1/4)_m, what would the switching do?

**Comment by c3d** [comment]
`ModeCycle` suggests a mode change, but this is really a value change.
I prefer `RepCycle` or maybe `ObjCycle`.

Tp amswer the question about units, I was thinking this would switch
between nearby SI units, i.e.

1km -> 1000m
1000km -> 1_000_000m -> 1Mm

For 1/4_m, I would expect 25cm -> 0.25m, but then I think that the
question is if there would also be a cycle of fraction vs. decimal.

Need to think more about this.

**Comment by c3d** [comment]
Finally settled on calling that function `Cycle`.
