### ISSUE TITLE
Seconds toggle in Settings-Status Bar doesn't clear

### ISSUE THREAD

**Issue by spiff72** [c3d/DB48X-on-DM42#275]
The toggle appears to work, but if you try to clear the "X" out of the Show Seconds in the status bar settings, it won't disappear.  It can actually be toggled, it just isn't reflected by the toggle correctly.

**Comment by camillew** [comment]
I believe this is a duplicate of #247, which is fixed in https://github.com/c3d/DB48X-on-DM42/commit/2d57b02a676d8721594a99b552218cdd9605dd94.

**Comment by spiff72** [comment]
thanks - i tried searching (i think) but didn't see it

**Comment by spiff72** [comment]
Closing
