### ISSUE TITLE
xth root of y doesn't work

### ISSUE THREAD

**Issue by spiff72** [c3d/DB48X-on-DM42#276]
Placing 8 on y and 3 on x and running the xth root of y operator from the KB (double-shift 1/x key) just results in a beep.  Even an empty stack just produces a beep (no error message on screen).

**Comment by camillew** [comment]
I think this is because the function is not implemented yet:
https://github.com/c3d/DB48X-on-DM42/blob/0112a598985b1ed929e360e9801d944b8d14c24f/src/menu.cc#L876

**Comment by spiff72** [comment]
Yep - Christophe suggested I add it in an email conversation, so I did...

**Comment by c3d** [comment]
Thanks @spiff72 for adding this.
