### ISSUE TITLE
Multiplying by -1 does nothing

### ISSUE THREAD

**Issue by camillew** [c3d/DB48X-on-DM42#288]
Running "-5 -1 *" returns -5. This seems to be due to the special casing of multiplication using the integer::is_one(), which is incorrect for neg_integer and would need to be specialized. I imagine that big_num may have a similar issue.

**Comment by camillew** [comment]
This issue is resolved by specializing the `neg_*` types in `bool object::is_one(bool error) const`, starting with
```
{
    id ty = type();
    switch(ty)
    {
    case ID_neg_integer:
    case ID_neg_bignum:
    case ID_neg_fraction:
        return false;
...
```

**Comment by c3d** [comment]
I have a fix ready, but it looks like you are quite ready to submit patches ;-)

**Comment by camillew** [comment]
Yes, I would be happy to try to send patches, but I am not yet able to compile Qt in such a way that it works with the simulator, which in turns prevents me from running/enriching test cases. Hopefully I'll get there soon :)
