### ISSUE TITLE
NEG on a polar complex converts it to rectangular

### ISSUE THREAD

**Issue by camillew** [c3d/DB48X-on-DM42#289]
This happens because NEG(x) is implemented as "0 - x", and the complex implementation of sums and differences forces a conversion to rectangular. 

Maybe NEG(x) could be updated to "-1 * x", so that polar representation would be preserved? (I am not sure if this would create other issues.) This would require https://github.com/c3d/DB48X-on-DM42/issues/288 to be fixed first.

**Comment by c3d** [comment]
Good catch, @camillew. I have a fix for that one. Also highlighted a "usual" problem of having forgotten that % was not a modulo...
