### ISSUE TITLE
Random reset on 0.4.8 (low battery?)

### ISSUE THREAD

**Issue by balta1980** [c3d/DB48X-on-DM42#476]
After a day of using 0.4.8 firmware:

[https://youtube.com/shorts/UOwYYszr4yU?si=w-_QFNlmRmH6zmhc](url)

After stopping using the calculator and powering off **for several minutes** and try to turn it on again it crashes and reboot.

Thank you.

**Comment by c3d** [comment]
Thanks for sharing the video. That is really weird. Mine has been running for over a week and I did not see that problem.

Did you reflash the QSPI (not just the PGM file)? Having a mismatched QSPI / PGM pair is not detected, and it can lead to random crashes like that.

**Comment by balta1980** [comment]
Thank you. Yes, in every release I flash QSPI and program files. I will do it again and I will let you know if this happens again.

**Comment by c3d** [comment]
Did you have the problem again?

I've been running 0.4.8 on battery and USB for nearly a week, restored it to factory settings, and I could not reproduce the problem.

**Comment by balta1980** [comment]
Just in case, I re flash QSPI and program but, and after a day I got same behavior than before. If I power off calculator and wait around 5 seconds and try to turn it on it reboot.

**Comment by balta1980** [comment]
Look at this new video [https://youtu.be/fW0FyyR8Stw?si=6y5BuLitEKg46MyS]()

**Comment by c3d** [comment]
Hmmm... I think that I have a new explanation. You battery seems to be very low. It's showing 2.4V. I've never been so low. Could you try replacing the battery and see if that helps?

I need to see what the DM42 does in that scenario. Out of curiosity, could you, with the same battery, reload the DM42 program and see if it complains? Or if it behaves normally?

**Comment by c3d** [comment]
In the other video, I can see the battery voltage dropping very quickly. It starts at 2.7V, but then it's down to 2.5 or less (lowest I saw was 2.241V, which is really low). Mine starts at 2.680, but then _increases_ to 2.702V or something like that.

I suspect that the loading of the off-image that occurs when you power off is actually somewhat CPU intensive, and might be draining an already dying battery.

In any case, it's not normal that the voltage would vary that much.

**Comment by c3d** [comment]
That being said, I find it suspect that the battery voltage is not drawn in gray, as it should if the DMCP `get_lowbat_state()` returned a low-bat state. Apparently, it does not.

I know that the C43 / C47 team had a lot of trouble getting the low-battery behaviour to be decent on this platform. See [this issue](https://gitlab.com/rpncalculators/wp43/-/issues/456) for an example.

**Comment by c3d** [comment]
Apparently, the problem [also exists with the stock DM42 firmware](https://forum.swissmicros.com/viewtopic.php?t=3432).

Notably, [this comment](https://forum.swissmicros.com/viewtopic.php?p=25705#p25705) states the following (emphasis mine):

> It seems there is no exact lower limit when the DM42 stops working
> confidentially. Mine (at 2064 mV) works/calculates perfect but **has troubles
> when switching to auto power off (resets to DMCP instead of suspend mode)**.

**Comment by balta1980** [comment]
After replacing the battery, no more problems. I am sorry for wasting your time. Thank you very much.

**Comment by c3d** [comment]
You did not waste my time at all. On the contrary, this led to an improvement of battery icon rendering that will make the low-battery situation more visible I am also considering forcing the machine to 'off' with a message in that case. So very useful information.
