### ISSUE TITLE
Additional spacing before decimal (DB48X-0.4.8 Diplay Issue)

### ISSUE THREAD

**Issue by BTF-NGU** [c3d/DB48X-on-DM42#489]
Setting:  Fix 4, Dig 0, Seps: 1,000.; 2.3

9.27 x 1000 = [9,270,.0000]

**Comment by c3d** [comment]
Thanks a lot for the report. This looks like a duplicate of #485. However, I thought that I had fixed it, and your example still shows the problem, presumably because of the trailing 0 on the left of the decimal separator.
