### ISSUE TITLE
Update units menu to reintroduce `cm` and other derived units

### ISSUE THREAD

**Issue by c3d** [c3d/DB48X-on-DM42#550]
After adding support for the units file, the menus were not reorganized to match what was there before.

Doing so would require the ability to add units that are shown only in menus, but not looked up as individual units. Units with a definition beginning with an `=` sign will only appear in menus, but will not be looked up.

**Comment by c3d** [comment]
Also, @spiff72 reported that there is a bogus `miUS` menu entry in the built-in database.

**Comment by spiff72** [comment]
Is there documentation of how to use the units file?  I see that there is an example in the repo, but is this a file that would be placed within the FAT folder structure, or is it read at compile time?

**Comment by c3d** [comment]
> Is there documentation of how to use the units file? I see that there is an example in the repo, but is this a file that would be placed within the FAT folder structure, or is it read at compile time?

It should be placed inside the `CONFIG` directory.
