### ISSUE TITLE
why does the cube root of -8 = NaN?

### ISSUE THREAD

**Issue by yeled** [c3d/DB48X-on-DM42#635]
I was reading https://forum.swissmicros.com/viewtopic.php?f=17&t=2820 and tried the cube root of -8 on a DM32, DM42, C47 and then I tried it on the DB48X (on a DM32)

All of them give either -2 or an imaginary number.

![Image](https://github.com/c3d/DB48X-on-DM42/assets/200421/085d4843-e15a-474a-af8a-b94b9a757546)

```
-8
3
1/x
```
(ignore my mislabled stickers)

**Comment by c3d** [comment]
The `NaN` result is a result of not catching numerical errors correctly for binary operations. You should get an `Argument outside domain` error.

I filed a separate bug on this specific problem (#639)

**Comment by c3d** [comment]
Please note that there is a specific `CBRT` function that computes the cube root, and will give you the `-2` result. I know that this is not what you were asking, but it's worth pointing out.

**Comment by c3d** [comment]
> I was reading https://forum.swissmicros.com/viewtopic.php?f=17&t=2820 and
> tried the cube root of -8 on a DM32, DM42, C47 and then I tried it on the
> DB48X (on a DM32)
>
> All of them give either -2 or an imaginary number.

Just curious, have you found a calculator that actually returns -2 for (-8)^(1/3)?

HP41: Data error
HP15C: Error 0
HP48: Complex number (principal solution)
HP50: Complex number.

It seems to me like Thomas Okken's answer in that thread is correct: -8^(1/3) is generally understood in terms of exp and log. With a fraction type, we could probably correctly define the expression `a^(b/c)`, though. Let me think about that.

**Comment by yeled** [comment]
in my collection:

TI Galaxy 67: -2
C47: -2
