### ISSUE TITLE
Spacing between digits shows odd spaces when in the 1.2E32 mode during entry

### ISSUE THREAD

**Issue by spiff72** [c3d/DB48X-on-DM42#643]
I have the following (hopefully relevant settings):
1 000 (use space as separator)
1.2E23 for exponent display
2.3 as decimal separator
Mant 3
Frac 3
Based 3
Exp 9
Dig 0

When I enter a number on the stack - eg 305E2051, the spaces that are inserted don't behave as I would expect them to.  The sequence with this number looks like this:
3
30
305
305E
30 5E2
305 E20
3 05E 205
30 5E2 051

It looks to me that it is treating the E as a digit, and applying spacing accordingly.  The exception is the 4th line above, where if this was the case, it seems like it should have shown 3 05E

Once the ENTER key is pressed, the spacing is correct, but I find this behavior somewhat jarring and unexpected.

In the 1.2x10^32 mode, it works as I would expect and spacing doesn't misbehave during entry.

**Comment by c3d** [comment]
Thanks for the report, @spiff72. I suspect that it incorrectly considers `E` as an hexadecimal digit. I'll try to fix it today.
