### ISSUE TITLE
HMS+ does not work as expected (based on my HP 42S experience)

### ISSUE THREAD

**Issue by jthole** [c3d/DB48X-on-DM42#662]
DM42 / v0.6.1

Convert 2.5 to HMS delivers 2:30:00 (correct).

Entering 1 on the stack, and selecting HMS+ delivers 2:00:00 (incorrect).

The alternative works, but is less practical:

Put 2.5_hms on the stack.
Put 1_hms on the stack.
Add both, and the result becomes 3.5_hms (or 3:30:00)

Edit: for the time being, I loaded the DM42 program again. I did not test if using 1.0000 instead of 1 works.

**Comment by c3d** [comment]
Incorrectly tested after what I thought was a minor edit, but included a copy-paste error.

Furthermore, re-reading the code, I realized that it was doing the HMS conversion for inputs backward.
