### ISSUE TITLE
Add test for cube root of -8

### ISSUE THREAD

**Issue by c3d** [c3d/DB48X-on-DM42#685]
Check that the cube root of -8 works, whether directly (i.e. `CBRT`) or indirectly (`-8 1/3 ^`). Whether the latter should work is to be discussed.

**Comment by jthole** [comment]
I think (-8 1/3 ^) should be consistent with historical HP calculators, and implement y^x as e^(x * ln(y)), which returns a complex result in this case. That would be consistent with the HP-48 and earlier calculators.

Edit: it seems currently only "-8+0i" gives the complex result; "-8" gives an "outside domain" error (there is something to say for that too, but it is not the way the HP-48 emulator on my iPhone handles it).
