### ISSUE TITLE
Trailing decimal not shown after `0`, e.g. in `0.2`

### ISSUE THREAD

**Issue by spiff72** [c3d/DB48X-on-DM42#726]
This is a tricky one to describe clearly, but I will give an example:

I just upgraded to 0.6.2 today, and I CANNOT confirm whether this issue was present in 0.6.1 or not.  

Imagine you have a super-simple program saved as a variable called 'INC20' (so that it is accessible from the variable as a soft-key):

`<< 0.2 + >>`

This works fine if the mode is set to 1.0->1. under the "SEPS" menu.  Running the program increments the first level of the stack by 0.2 as expected.

However, if you switch to the 1.0->1 mode option, running the program increments the stack by 0.2, UNLESS you have a zero on the stack.  In this case, the result is 02 instead of 0.2 

I recalled the program stored in 'INC20', the result is:

`<< 02 + >>`

Additionally, if you are in 1.0->1. mode, and enter some values like 0.2 0.5 0.42 on the stack, and then change to 1.0->1 mode, the values entered change to 02 05 042 and will revert back to the decimal entered values if the mode is switched back to the original values.

Is this expected behavior or a bug?  I'm assuming this is an integer/real number thing, but it confused me to look at one of these programs and see the 02 instead of 0.2 value.

**Comment by c3d** [comment]
This is definitely a bug. It looks like the `.` is not printed in a case where it should be.

**Comment by c3d** [comment]
Original title "Unexpected/confusing behavior of the 1.0->1. vs 1.0->1 option settings under SEPS menu".

I will shorten it to describe what I believe is happening.

**Comment by c3d** [comment]
Reduced test case: `0.2` displays as `02` when `NoTrailingDecimal` option is active.

**Comment by c3d** [comment]
This was an off-by-one in the test checking if the value was less than 1.
Fixed, will be published with 0.6.3.
