### ISSUE TITLE
Premature gc at purge?

### ISSUE THREAD

**Issue by lenborje** [c3d/DB48X-on-DM42#854]
Purging an object that has been recalled to the stack leaves the stack object unusable. I suspect the object is gc’d away, making the pointer on the stack invalid.

Example:

| Commands | Comment
|-|-
| `{} ’P’ STO`     |  Create an empty list and store in P
| `P`                    | Recall P to stack
| `’P’ PURGE`     |  Purge P. Object on stack now shown as XOR

DB48X v0.7.1

**Comment by c3d** [comment]
Hah! Good catch, @lenborje. I'll take a look.

**Comment by c3d** [comment]
Code inspection shows that:

* `runtime::clone_global` is not called on `Purge`, only on `Store`...
  That explaines the reported behaviour.

* The scanning for `clone_global` stops too early. It does not cover directories, which may very well reference global objects. It does not cover return addresses, but they too can now refer to (the inside of ) global objects, typically programs.

* The scanning also only considers an identical address, but it needs to cover anything in the object, as if you extract an item from a list. A test example would be:

  ```
  { 1 2 3 4 } 'X' Sto
  X X 1 GET X 2 GET X 3 GET X 4 GET
  'X' Purge
  ```

In such a case, we need to clone all the objects, but while preserving the structure of the object.

**Comment by c3d** [comment]
@lenborje, I think that I have a fix, so I'm marking the issue as "done". It will be in the next release (0.7.3) probably this week-end. So marking the issue as `done`.

**Comment by lenborje** [comment]
Thank you for the quick fix!
