### ISSUE TITLE
Graphical glitch in status bar

### ISSUE THREAD

**Issue by spiff72** [c3d/DB48X-on-DM42#922]
I am finding that with version 0.7.4, if I press the VAR key to show the variable menu, there is a graphical glitch present in the status bar on the far left.  It seems to distort the first part of the current date.  See attached photo (I don't know if it shows up in a screenshot because I can't recall the method of creating one).  I do not know if this glitch was present in previous versions.

Additionally, this only occurs when the stack is full enough to overflow at least one item off screen.  If there are no stack items above the uppermost visible stack level, the glitch doesn't appear.  Oddly, it also doesn't seem to appear when there is overflow AND the version command output is present at the first level.  If the output of the VERSION command is dropped (and there is still overflow), the glitch comes back.

Pressing EXIT to hide the VAR menu at the bottom clears up the glitch.  Pressing VAR brings it back.
![IMG_0934](https://github.com/c3d/db48x/assets/11482743/3344dd9f-1ab8-469e-8d52-2561b2bfd96b)

**Comment by c3d** [comment]
Ah, good catch!

What you see is the stack level, level 5 in your photo, you can somewhat make the 5 if you look carefully. This explains why you only see it if the stack is deep enough, or if the content of the stack (e.g. the result of `VERSION`) makes it so that the level number is not seen.

**Comment by c3d** [comment]
I have a fix, it will be in 0.7.6. Thanks for reporting.

**Comment by spiff72** [comment]
Ah - so I am seeing a black 5 superimposed over the light 5 (part of the date)?
