### ISSUE TITLE
`Put` command incorrect boundary check (corruption, out of memory)

### ISSUE THREAD

**Issue by mahi2003** [c3d/DB48X-on-DM42#954]
Stack:
```
{ 1 2 3 }
4
```
[Get] (from LIST menu) → Index out of range (=correct)

```
{ 1 2 3 }
4
4
```
[Put] (from LIST menu) → Out of memory + unwanted stack alteration

**Comment by c3d** [comment]
Original user report is here

https://www.hpmuseum.org/forum/thread-20157-post-187618.html#pid187618

**Comment by mahi2003** [comment]
Confirmed fixed in 0.7.7!
