### ISSUE TITLE
Negative fraction may display two minus signs

### ISSUE THREAD

**Issue by mahi2003** [c3d/DB48X-on-DM42#955]
When the stack is in graphical mode, a negative fraction like `-1/2` is wrongly displayed with 2 minus signs:
```
  -1
- ——
   2
```
The same as an equation with division, `'-1÷2'`, is displayed correctly:
```
-1
——
 2
```

**Comment by c3d** [comment]
Original user report is here

https://www.hpmuseum.org/forum/thread-20157-post-187618.html#pid187618

**Comment by mahi2003** [comment]
Confirmed fixed in 0.7.7!

**Comment by c3d** [comment]
There is a [comment on YouTube](https://www.youtube.com/watch?v=5iSjn6pGhqA&lc=UgwKLYdnhXYaOWMFPQp4AaABAg) that suggests this still exists on 0.7.12. Closing this one, I will let the original poster reopen or create new issue.

**Comment by c3d** [comment]
User confirmed he was on 0.7.4, i.e. prior to the fix being applied.
