### ISSUE TITLE
`Bad argument type` for `Cycle` on constant

### ISSUE THREAD

**Issue by c3d** [c3d/DB48X-on-DM42#957]
When given a symbolic constant, `Cycle` gives a `Bad argument type`. Question is what the correct behavior should be (do nothing, behave like for equations, etc).

**Comment by c3d** [comment]
Original bug report is here

https://www.hpmuseum.org/forum/thread-20157-post-187618.html#pid187618

**Comment by mahi2003** [comment]
Confirmed fixed in 0.7.7!
