### ISSUE TITLE
`mod` does not work correctly in algebraic entry

### ISSUE THREAD

**Issue by mahi2003** [c3d/DB48X-on-DM42#962]
The `mod` (modulo) function is implemented as an operator in algebraic entry, but it does not work correctly:

`'` `X` `mod` `Y` `ENTER` → `'XmodY'` (interpret as variable name _XmodY_ instead of mathematical operation)
`'` `9` `mod` `3` `ENTER` → `'mod3'` (9 is seemingly lost, but when pressing `EVAL` it is mysteriously put on stack level 2)

When you put a space before and after `mod`, it works correctly. Maybe DB48/50X should automatically insert spaces when pressing `mod` in algebraic entry?

Update: The same issue happens with operators like `and`, `or` and probably many others.

**Comment by mahi2003** [comment]
Duplicate of #906

**Comment by mahi2003** [comment]
This may be a duplicate of #906, but I'm not sure. #906 seems to be about visualization while this is about entry in algebraic mode.

**Comment by c3d** [comment]
Hi @mahi2003, could you please try again with 0.7.7?

Issue #906 is indeed about visualization, but with the result that it actually also solves that particular problem (at least for me).

**Comment by c3d** [comment]
Oh, @mahi2003I think that I see what you mean. The problem is if you type `mod` with the menu entry, not if you manually type it.

Something like this key sequence (using letters for simplicity)

```
F X SHIFT SHIFT L F3 Y
```

This indeed does not insert spaces around `mod`.

**Comment by mahi2003** [comment]
Confirmed fixed in 0.7.8!
