### ISSUE TITLE
Add units to existing equations

### ISSUE THREAD

**Issue by c3d** [c3d/DB48X-on-DM42#968]
Add units to existing equations to make sure that they work in the solver.

The underlying mechanism works, but the equations themselves where not updated.

Reported by mahi on [HP Museum thread][report]

[report]: https://www.hpmuseum.org/forum/thread-20157-post-187861.html#pid187861

**Comment by mahi2003** [comment]
Confirmed fixed in 0.7.8!

:heavy_check_mark: `'(E_J)=(m_kg)∙c↑2'`: Setting m = 2 (automatically makes it 2_kg) solves E = 1.7975E17_J
:heavy_check_mark: `'E=m∙c↑2'`: Setting m = 2 solves E = 1.7975E17

So, it works both with and without units.
