### ISSUE TITLE
`ConvertToUnitPrefix` is very slow on real calculator

### ISSUE THREAD

**Issue by c3d** [c3d/DB48X-on-DM42#976]
Running `ConvertToUnitPrefix` for the value corresponding to the power generated for 3kg of matter takes several seconds on a real calculator.

**Comment by mahi2003** [comment]
A random grab of units (on USB power). I measured the time by executing `Cycle` which on its turn calls `ConvertToUnitPrefix`:

`1_F` ~40 s
`1_V` ~15 s
`1_P` ~8 s
`1_bar` ~8 s
`1_W` ~7 s
`1_cal` ~4 s
`1_N` ~3 s
`1_l` ~1 s
`1_mph` ~1 s
`1_ha` ~1 s
`1_t` ~1 s
`1_s` ~0.5 s
`1_m` ~0.2 s
`1_USD` ~0 s (does not call `ConvertToUnitPrefix` I think)

**Comment by c3d** [comment]
I tracked it back to expression simplification that was added in 0.7.8, and applies to every single unit operation while factoring out units, making the factoring super slow.

I thought it would be fixed on `dev` now, but experimentation shows it is not, so there is another problem that needs fixing.

**Comment by c3d** [comment]
Expression simplification was still happening for the evaluation of the definition of a unit.

**Comment by mahi2003** [comment]
It's much better now in 0.7.9, but still slow for certain conversions. Especially on battery power.

`1_F` `Cycle` → `1/10_daF` takes 4 seconds on battery power. That's a bit excessive to basically divide by 10...
