### ISSUE TITLE
Entering phasors with explicit degrees sign does not work

### ISSUE THREAD

**Issue by mahi2003** [c3d/DB48X-on-DM42#983]
I just watched the 0.7.8 demo on Youtube. One of the new features is the ability to enter a polar value with a different angle mode than currently set. This does not seem to work in all cases.

_< represents the angle symbol - I did not find the correct character_

With the calculator in `Grads` mode:

`1` `<` `45` `Deg` `ENTER` → :x: I expect `1<50g` on the stack, but instead I get `1<45g`. It's as if the `Deg` action was ignored even though the entry looked like `1<45°`prior to hitting ENTER.

The other way around works fine, though. With the calculator in `Deg`(rees) mode:

`1` `<` `50` `Grads` `ENTER`  → :heavy_check_mark: `1<45°` is put on the stack.

**Comment by mahi2003** [comment]
Update: Further testing shows that only `Deg` is affected.

Entering polar values with `Grad`, `Rad` and `n×π` while the current angle mode is something else, works fine.

**Comment by c3d** [comment]
Still reproducing, fix is now under test.

**Comment by mahi2003** [comment]
✔️ Confirmed fixed in 0.7.9!
