### ISSUE TITLE
Entering phasor without angle gives internal error

### ISSUE THREAD

**Issue by mahi2003** [c3d/DB48X-on-DM42#989]
_< represents the angle symbol_

`1` `<` `ENTER` → :x: Internal error, please report

Not sure what the desired behavior should be. Error or `1<0°`?

Note that entering `<` `30` does automatically insert magnitude 1: `1<30°`

**Comment by c3d** [comment]
Thanks for reporting, @mahi2003. You will earn a special mention in the release notes for the next release ;-)

Problem confirmed and identified, will be fixed in the next release.

**Comment by c3d** [comment]
BTW, the fix generates a syntax error in that case.

**Comment by mahi2003** [comment]
✔️ Confirmed fixed in 0.7.9!

Both cases now return a syntax error
