### ISSUE TITLE
`sqrt` and `xroot` do not work on values with units

### ISSUE THREAD

**Issue by mahi2003** [c3d/DB48X-on-DM42#990]
`2_m` `x²` → `4_m²` ✔️
`4_m²` `√x` → :x: Bad argument type
`8_m³` `3` `x√y` → :x: Bad argument type (and input values lost)

I also noticed that the HP 48/50 can apply functions like `FLOOR`, `RND`, `MIN`, etc to values with units whereas DB48/50X always returns bad argument type.

Interesting is `mod`. In DB48/50X:

`13_m` `6` `mod` → `'(13_m) mod 6'`

It does not appear to be possible to evaluate this (`→Num` doesn't work either). The HP 48/50 returns a bad argument type error in this scenario.

**Comment by c3d** [comment]
Thanks a lot for reporting that, @mahi2003. I will try to implement it for the next release. It's not very complicated.

**Comment by c3d** [comment]
Problem presumably also exists for power and cube root.

(Edit: Does not exist for power, including fractional ones)

**Comment by mahi2003** [comment]
✔️ Confirmed fixed in 0.7.9 for `sqrt`, `cbrt` and `xroot`!

Shouldn't it be implemented for `FLOOR`, `RND`, `MIN`, etc like on the HP 48/50?
