### ISSUE TITLE
Right shift indicator stays lit after triple shift

### ISSUE THREAD

**Issue by mahi2003** [c3d/DB48X-on-DM42#991]
When you triple press the shift key rapidly, the right shift indicator stays lit. It may take a few tries, but it's really easy to reproduce. If you have a multi-line menu open, the calculator correctly highlights the bottom row and pressing a menu soft key executes the bottom row one (in other words, the shift indicator was wrong).

**Comment by c3d** [comment]
Thanks for reporting, @mahi2003. Reproduced and confirmed.

**Comment by c3d** [comment]
Fix implemented. What matters is not pressing shift rapidly, but that no other refresh event for the header area happens after clearing the shift & alpha indicators.

The reason was that the screen refresh area for no indicators was empty, so the `refresh_dirty` function was doing nothing.

**Comment by mahi2003** [comment]
✔️ Confirmed fixed in 0.7.9!
