### ISSUE TITLE
Purge does not work on list

### ISSUE THREAD

**Issue by guirossibrum** [c3d/DB48X-on-DM42#997]
Hello Christophe, on v 0.7.8 now
in HP48G, you can open a list and add your variables { A B C} and then purge them. this does not work on DB48X.
one suggestion is to add the PURGE command to the clear menu to speed access.

thank you

**Comment by c3d** [comment]
Indeed, this is a known not-yet-implemented feature

**Comment by c3d** [comment]
Adding `Purge` to the clear menu makes a lot of sense.
It is already in the `Mem` menu, but DB48X has many menu duplicates.
